# Generated by Django 5.0.1 on 2025-09-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='about',
            name='subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='values_intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
